SELECT ENCODE(ASSET.POLICY,'hex') AS POLICY_ID,
	ENCODE(ASSET.NAME,'hex') AS ASSET_NAME,
	"asset"."fingerprint",
	SUM(MA_TX_MINT.QUANTITY) AS QUANTITY,
	COUNT(*) AS MINT_OR_BURN_COUNT,
	(SELECT ENCODE(TX.HASH,'hex')
		FROM TX
		INNER JOIN MA_TX_MINT ON TX.ID = MA_TX_MINT.TX_ID
		INNER JOIN MULTI_ASSET AS ASSET ON ASSET.ID = MA_TX_MINT.IDENT
		WHERE ASSET.FINGERPRINT = 'asset1uq7kmkq4re85zgxtuzweayl23lgs7tjytw24u2'
		ORDER BY TX.ID ASC
		LIMIT 1) AS INITIAL_MINT_TX_HASH,

	(SELECT TX_METADATA.JSON || JSONB_BUILD_OBJECT('key',TX_METADATA.KEY)
		FROM TX_METADATA
		INNER JOIN MA_TX_MINT ON TX_METADATA.TX_ID = MA_TX_MINT.TX_ID
		INNER JOIN MULTI_ASSET AS ASSET ON ASSET.ID = MA_TX_MINT.IDENT
		WHERE ASSET.FINGERPRINT = 'asset1uq7kmkq4re85zgxtuzweayl23lgs7tjytw24u2'
		LIMIT 1) AS ON_CHAIN_METADATA
FROM "ma_tx_mint"
INNER JOIN "multi_asset" AS "asset" ON "asset"."id" = "ma_tx_mint"."ident"
WHERE ASSET.FINGERPRINT = 'asset1uq7kmkq4re85zgxtuzweayl23lgs7tjytw24u2'
GROUP BY "asset"."policy",
	"asset"."name",
	"asset"."fingerprint"
